export const searchCollectionSchema = {
  type: "object",
  required: ["page", "results", "total_pages", "total_results"],
  properties: {
    page: { type: "number" },
    results: {
      type: "array",
      items: {
        type: "object",
        required: [
          "adult",
          "backdrop_path",
          "id",
          "name",
          "original_language",
          "original_name",
          "overview",
          "poster_path",
        ],
        properties: {
          adult: { type: "boolean" },
          backdrop_path: {
            oneOf: [{ type: "string" }, { type: "null" }],
          },
          id: { type: "number" },
          name: { type: "string" },
          original_language: { type: "string" },
          original_name: { type: "string" },
          overview: { type: "string" },
          poster_path: {
            oneOf: [{ type: "string" }, { type: "null" }],
          },
        },
        additionalProperties: false,
      },
    },
    total_pages: { type: "number" },
    total_results: { type: "number" },
  },
  additionalProperties: false,
};

export const collectionDetailsSchema = {
  type: "object",
  required: [
    "id",
    "name",
    "original_language",
    "original_name",
    "overview",
    "poster_path",
    "backdrop_path",
    "parts",
  ],
  properties: {
    id: { type: "number" },
    name: { type: "string" },
    original_language: { type: "string" },
    original_name: { type: "string" },
    overview: { type: "string" },
    poster_path: { oneOf: [{ type: "string" }, { type: "null" }] },
    backdrop_path: { oneOf: [{ type: "string" }, { type: "null" }] },
    parts: {
      type: "array",
      items: {
        type: "object",
        required: [
          "adult",
          "backdrop_path",
          "id",
          "title",
          "original_title",
          "overview",
          "poster_path",
          "media_type",
          "original_language",
          "genre_ids",
          "popularity",
          "release_date",
          "video",
          "vote_average",
          "vote_count",
        ],
        properties: {
          adult: { type: "boolean" },
          backdrop_path: { oneOf: [{ type: "string" }, { type: "null" }] },
          id: { type: "number" },
          title: { type: "string" },
          original_title: { type: "string" },
          overview: { type: "string" },
          poster_path: { oneOf: [{ type: "string" }, { type: "null" }] },
          media_type: { type: "string", enum: ["movie"] },
          original_language: { type: "string" },
          genre_ids: { type: "array", items: { type: "number" } },
          popularity: { type: "number" },
          release_date: { type: "string", pattern: "^\\d{4}-\\d{2}-\\d{2}$" },
          video: { type: "boolean" },
          vote_average: { type: "number" },
          vote_count: { type: "number" },
        },
        additionalProperties: false,
      },
    },
  },
  additionalProperties: false,
};
